ls:
  .maddo.js: kebab-case
  .js: kebab-case
  _test.js: kebab-case

  .dir: kebab-case

  lib:
    application:
      preHandlers:
        .dir: camelCase
      simulateErrors:
        .dir: camelCase

    infrastructure:
      orm-models:
        .js: PascalCase

  tests:
    integration:
      application:
        campaignParticipations:
          .dir: camelCase

  src:
    models:
      .js: PascalCase

ignore:
  - .git
  - node_modules
  - datamart/migrations
  - db/migrations
  - db/seeds
  - scripts
  - codemods
